export const PODCAST_EPISODES = [
  {
    id: "pod-1",
    episodeNumber: 1,
    title: "The Power of Vulnerability",
    description: "Brené Brown explains why opening up about our fears and imperfections actually makes us stronger — not weaker. One of the most-watched TED Talks ever.",
    host: "Brené Brown · TED",
    spotifyUrl: "https://open.spotify.com/show/4P86ZzHf7EOlRG7do9LkKZ",
    youtubeUrl: "https://www.youtube.com/watch?v=iCvmsMzlF7o",
  },
  {
    id: "pod-2",
    episodeNumber: 2,
    title: "What Makes a Good Life?",
    description: "Harvard's longest study on happiness (75 years) reveals the one thing that keeps us healthier and happier as we age. Spoiler: it's not money.",
    host: "Robert Waldinger · TED",
    spotifyUrl: "https://open.spotify.com/show/1CfW319UkBMVGCXAvJbRcT",
    youtubeUrl: "https://www.youtube.com/watch?v=8KkKuTCFvzI",
  },
  {
    id: "pod-3",
    episodeNumber: 3,
    title: "How to Rewire Your Brain for Less Anxiety",
    description: "Neuroscientist Andrew Huberman breaks down what anxiety actually is in your brain and shares science-backed tools to calm your nervous system fast.",
    host: "Andrew Huberman · Huberman Lab",
    spotifyUrl: "https://open.spotify.com/show/79CkJF3UJTHFV8Dse3Oy0P",
    youtubeUrl: "https://www.youtube.com/@hubermanlab",
  },
  {
    id: "pod-4",
    episodeNumber: 4,
    title: "Stop Running From Your Emotions",
    description: "Jay Shetty talks about why avoiding difficult feelings makes them louder — and how to actually process them so you can move forward with clarity.",
    host: "Jay Shetty · On Purpose",
    spotifyUrl: "https://open.spotify.com/show/5EqqB52m2bsr4k1Ii7sStc",
    youtubeUrl: "https://www.youtube.com/@jayshetty",
  },
  {
    id: "pod-5",
    episodeNumber: 5,
    title: "Why Loneliness Is a Health Crisis",
    description: "Dan Harris sits down with researchers to unpack why loneliness is as damaging as smoking — and the small daily habits that genuinely help.",
    host: "Dan Harris · 10% Happier",
    spotifyUrl: "https://open.spotify.com/show/1CfW319UkBMVGCXAvJbRcT",
    youtubeUrl: "https://www.youtube.com/@10percenthappier",
  },
  {
    id: "pod-6",
    episodeNumber: 6,
    title: "Sleep, Stress & Your Mental Health",
    description: "Poor sleep and high stress feed each other in a vicious cycle. Huberman explains the neuroscience and gives simple, free tools to break it tonight.",
    host: "Andrew Huberman · Huberman Lab",
    spotifyUrl: "https://open.spotify.com/show/79CkJF3UJTHFV8Dse3Oy0P",
    youtubeUrl: "https://www.youtube.com/@hubermanlab",
  },
];
