export interface Psychologist {
  id: string;
  name: string;
  title: string;
  image: string;
  verified: boolean;
  rating: number;
  reviewCount: number;
  location: string;
  priceRange: string;
  languages: string[];
  conditions: string[];
  about: string;
  experience: number;
  sessionDuration: string;
  nextAvailable: string;
  licenseNumber?: string;
  highlights?: { icon: string; label: string; color: string }[];
  photos?: string[];
  insurances?: string[];
  testimonials?: { name: string; text: string; role: string; image: string }[];
  socials?: { facebook?: string; linkedin?: string; instagram?: string; website?: string; email?: string; phone?: string };
  education?: { degree: string; school: string; year: string }[];
  qualifications?: { name: string; issuer: string }[];
}

export const psychologists: Psychologist[] = [
  // --- United States ---
  {
    id: "us-1",
    name: "Dr. Sarah Thompson",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 124,
    location: "New York, United States",
    priceRange: "$150 - $250",
    languages: ["English", "Spanish"],
    conditions: ["Anxiety", "Depression", "Trauma"],
    about: "Dr. Sarah Thompson is a Clinical Psychologist with over 10 years of experience specializing in anxiety, depression, and trauma.",
    experience: 10,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    licenseNumber: "PSY-NY-12345",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }, { icon: "Star", label: "Top Choice", color: "bg-teal-100 text-teal-800" }],
    photos: ["https://images.unsplash.com/photo-1516357231954-91487b459602?auto=format&fit=crop&q=80&w=600&h=400"],
    insurances: ["Aetna", "BlueCross", "Cigna"]
  },
  {
    id: "us-2",
    name: "Dr. Michael Chen",
    title: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 89,
    location: "San Francisco, United States",
    priceRange: "$200 - $350",
    languages: ["English", "Mandarin"],
    conditions: ["ADHD", "Bipolar Disorder"],
    about: "Dr. Michael Chen takes a holistic approach to mental health, combining medication management with psychotherapy.",
    experience: 8,
    sessionDuration: "45 min",
    nextAvailable: "In 2 days",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "us-3",
    name: "Ms. Emily Rodriguez",
    title: "Family Therapist",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 65,
    location: "Austin, United States",
    priceRange: "$100 - $180",
    languages: ["English", "Spanish"],
    conditions: ["Family Conflict", "Relationship Issues"],
    about: "Dedicated to helping couples and families improve communication and resolve conflicts.",
    experience: 6,
    sessionDuration: "60 min",
    nextAvailable: "Today",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },

  // --- United Kingdom ---
  {
    id: "uk-1",
    name: "Dr. Arthur Pendelton",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 40,
    location: "London, United Kingdom",
    priceRange: "£120 - £180",
    languages: ["English"],
    conditions: ["Anxiety", "Work Stress"],
    about: "Specializing in cognitive behavioral therapy for professionals experiencing high stress.",
    experience: 15,
    sessionDuration: "50 min",
    nextAvailable: "Wednesday",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "uk-2",
    name: "Dr. Aisha Patel",
    title: "Child Psychologist",
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 5.0,
    reviewCount: 110,
    location: "Manchester, United Kingdom",
    priceRange: "£100 - £150",
    languages: ["English", "Gujarati", "Hindi"],
    conditions: ["Child Development", "Autism"],
    about: "Expert in child development and supporting neurodiverse children and their families.",
    experience: 12,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Star", label: "Top Rated", color: "bg-teal-100 text-teal-800" }]
  },
  {
    id: "uk-3",
    name: "Mr. Oliver Smith",
    title: "Psychotherapist",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.6,
    reviewCount: 25,
    location: "Edinburgh, United Kingdom",
    priceRange: "£90 - £130",
    languages: ["English"],
    conditions: ["Depression", "Grief"],
    about: "Compassionate support for those navigating loss and difficult life transitions.",
    experience: 7,
    sessionDuration: "50 min",
    nextAvailable: "Today",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },

  // --- Somalia ---
  {
    id: "so-1",
    name: "Dr. Hassan Abdi",
    title: "Trauma Specialist",
    image: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 5.0,
    reviewCount: 82,
    location: "Mogadishu, Somalia",
    priceRange: "$50 - $100",
    languages: ["Somali", "English", "Arabic"],
    conditions: ["Trauma", "PTSD", "Anxiety"],
    about: "Dr. Abdi is a renowned expert in trauma recovery, working with communities to heal from conflict and displacement.",
    experience: 20,
    sessionDuration: "60 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "so-2",
    name: "Ms. Faduma Ali",
    title: "Counseling Psychologist",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 45,
    location: "Hargeisa, Somalia",
    priceRange: "$40 - $80",
    languages: ["Somali", "English"],
    conditions: ["Family Conflict", "Women's Issues"],
    about: "Providing a safe space for women and families to discuss mental health and social challenges.",
    experience: 8,
    sessionDuration: "50 min",
    nextAvailable: "Today",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "so-3",
    name: "Dr. Ahmed Omar",
    title: "Clinical Psychiatrist",
    image: "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&q=80&w=300&h=300",
    verified: false,
    rating: 4.7,
    reviewCount: 30,
    location: "Garowe, Somalia",
    priceRange: "$60 - $120",
    languages: ["Somali", "Arabic"],
    conditions: ["Depression", "Schizophrenia"],
    about: "Specializing in severe mental health disorders and community rehabilitation programs.",
    experience: 15,
    sessionDuration: "45 min",
    nextAvailable: "Next Week"
  },

  // --- Kenya ---
  {
    id: "ke-1",
    name: "Dr. Wangari Maathai",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1589156280159-27698a70f29e?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 150,
    location: "Nairobi, Kenya",
    priceRange: "KES 3000 - 5000",
    languages: ["English", "Swahili"],
    conditions: ["Anxiety", "Depression", "Stress"],
    about: "Dr. Maathai is a leading psychologist in Nairobi, known for her empathetic approach and advocacy for mental wellness.",
    experience: 18,
    sessionDuration: "60 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "ke-2",
    name: "Mr. Jomo Kenyatta",
    title: "Addiction Counselor",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 60,
    location: "Mombasa, Kenya",
    priceRange: "KES 2500 - 4000",
    languages: ["English", "Swahili"],
    conditions: ["Addiction", "Substance Abuse"],
    about: "Helping individuals overcome addiction through personalized counseling and support groups.",
    experience: 10,
    sessionDuration: "50 min",
    nextAvailable: "Today",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "ke-3",
    name: "Ms. Amani Njoroge",
    title: "Child Therapist",
    image: "https://images.unsplash.com/photo-1522512119668-005521e9f450?auto=format&fit=crop&q=80&w=300&h=300",
    verified: false,
    rating: 4.8,
    reviewCount: 40,
    location: "Kisumu, Kenya",
    priceRange: "KES 2000 - 3500",
    languages: ["English", "Luo", "Swahili"],
    conditions: ["Child Development", "School Issues"],
    about: "Passionate about helping children navigate developmental challenges and school-related stress.",
    experience: 6,
    sessionDuration: "45 min",
    nextAvailable: "Wednesday"
  },

  // --- Turkey ---
  {
    id: "tr-1",
    name: "Dr. Mehmet Yilmaz",
    title: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 200,
    location: "Istanbul, Turkey",
    priceRange: "TRY 800 - 1500",
    languages: ["Turkish", "English", "German"],
    conditions: ["Anxiety", "OCD", "Depression"],
    about: "Dr. Yilmaz combines pharmacotherapy with psychotherapy to effectively treat mood and anxiety disorders.",
    experience: 22,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "tr-2",
    name: "Ms. Elif Demir",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1534751516042-4c2452913bc8?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 95,
    location: "Ankara, Turkey",
    priceRange: "TRY 600 - 1000",
    languages: ["Turkish", "English"],
    conditions: ["Relationship Issues", "Trauma"],
    about: "Elif specializes in EMDR therapy for trauma and helps couples restore intimacy and trust.",
    experience: 9,
    sessionDuration: "60 min",
    nextAvailable: "Today",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "tr-3",
    name: "Dr. Can Kaya",
    title: "Psychotherapist",
    image: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 50,
    location: "Izmir, Turkey",
    priceRange: "TRY 500 - 900",
    languages: ["Turkish", "English"],
    conditions: ["Stress", "Burnout"],
    about: "Helping professionals manage workplace stress and burnout through cognitive behavioral techniques.",
    experience: 7,
    sessionDuration: "50 min",
    nextAvailable: "Friday"
  },

  // --- Saudi Arabia ---
  {
    id: "sa-1",
    name: "Dr. Omar Al-Fayed",
    title: "Consultant Psychiatrist",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 5.0,
    reviewCount: 180,
    location: "Riyadh, Saudi Arabia",
    priceRange: "SAR 500 - 900",
    languages: ["Arabic", "English"],
    conditions: ["Depression", "Anxiety", "Bipolar Disorder"],
    about: "Leading psychiatrist in Riyadh with extensive experience in treating complex mood disorders.",
    experience: 25,
    sessionDuration: "45 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "sa-2",
    name: "Ms. Fatima Al-Saud",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 110,
    location: "Jeddah, Saudi Arabia",
    priceRange: "SAR 400 - 700",
    languages: ["Arabic", "English", "French"],
    conditions: ["Family Conflict", "Child Development"],
    about: "Specializing in family dynamics and child psychology, offering a culturally sensitive approach.",
    experience: 12,
    sessionDuration: "60 min",
    nextAvailable: "Today",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "sa-3",
    name: "Dr. Youssef Karim",
    title: "Psychotherapist",
    image: "https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?auto=format&fit=crop&q=80&w=300&h=300",
    verified: false,
    rating: 4.6,
    reviewCount: 40,
    location: "Dammam, Saudi Arabia",
    priceRange: "SAR 350 - 600",
    languages: ["Arabic", "English"],
    conditions: ["Addiction", "Stress"],
    about: "Dedicated to helping young adults navigate life transitions and substance use challenges.",
    experience: 6,
    sessionDuration: "50 min",
    nextAvailable: "Sunday"
  },

  // --- China ---
  {
    id: "cn-1",
    name: "Dr. Wei Zhang",
    title: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 90,
    location: "Beijing, China",
    priceRange: "¥500 - ¥800",
    languages: ["Mandarin", "English"],
    conditions: ["Anxiety", "Sleep Disorders"],
    about: "Expert in treating sleep disorders and anxiety using a combination of TCM principles and modern psychiatry.",
    experience: 15,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow"
  },
    {
    id: "cn-2",
    name: "Ms. Li Na",
    title: "Counselor",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 60,
    location: "Shanghai, China",
    priceRange: "¥400 - ¥700",
    languages: ["Mandarin", "English"],
    conditions: ["Stress", "Career Counseling"],
    about: "Helping professionals in high-pressure environments find balance and career satisfaction.",
    experience: 8,
    sessionDuration: "60 min",
    nextAvailable: "Today"
  },
  {
    id: "cn-3",
    name: "Dr. Chen Bo",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 130,
    location: "Guangzhou, China",
    priceRange: "¥600 - ¥1000",
    languages: ["Mandarin", "Cantonese", "English"],
    conditions: ["Depression", "Trauma"],
    about: "Cognitive behavioral therapy specialist for depression and PTSD.",
    experience: 18,
    sessionDuration: "50 min",
    nextAvailable: "Wednesday"
  },

    // --- India ---
  {
    id: "in-1",
    name: "Dr. Priya Sharma",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 210,
    location: "Mumbai, India",
    priceRange: "₹1500 - ₹2500",
    languages: ["English", "Hindi", "Marathi"],
    conditions: ["Anxiety", "Relationship Issues", "Depression"],
    about: "Dr. Sharma is a renowned psychologist helping couples and individuals find harmony in their relationships and lives.",
    experience: 14,
    sessionDuration: "60 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "in-2",
    name: "Dr. Rahul Verma",
    title: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 150,
    location: "Delhi, India",
    priceRange: "₹2000 - ₹3500",
    languages: ["English", "Hindi"],
    conditions: ["Bipolar Disorder", "Schizophrenia"],
    about: "Expert in managing severe mental health conditions with compassion and medical expertise.",
    experience: 20,
    sessionDuration: "45 min",
    nextAvailable: "Today"
  },
   {
    id: "in-3",
    name: "Ms. Ananya Gupta",
    title: "Counselor",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 80,
    location: "Bangalore, India",
    priceRange: "₹1200 - ₹2000",
    languages: ["English", "Hindi", "Kannada"],
    conditions: ["Stress", "Work-Life Balance"],
    about: "Helping tech professionals manage burnout and stress.",
    experience: 6,
    sessionDuration: "50 min",
    nextAvailable: "Friday",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },

  // --- Australia ---
  {
    id: "au-1",
    name: "Dr. Jack Thompson",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 95,
    location: "Sydney, Australia",
    priceRange: "$180 - $280",
    languages: ["English"],
    conditions: ["Trauma", "Anxiety"],
    about: "Specializing in helping veterans and first responders recover from PTSD.",
    experience: 12,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "au-2",
    name: "Ms. Olivia Wilson",
    title: "Child Psychologist",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 70,
    location: "Melbourne, Australia",
    priceRange: "$160 - $240",
    languages: ["English"],
    conditions: ["Child Development", "Behavioral Issues"],
    about: "Works with children and schools to improve learning and behavioral outcomes.",
    experience: 9,
    sessionDuration: "50 min",
    nextAvailable: "Today"
  },
  {
    id: "au-3",
    name: "Mr. Lucas Brown",
    title: "Counselor",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.6,
    reviewCount: 45,
    location: "Brisbane, Australia",
    priceRange: "$120 - $180",
    languages: ["English"],
    conditions: ["Addiction", "Men's Health"],
    about: "Supporting men in overcoming addiction and mental health stigma.",
    experience: 5,
    sessionDuration: "60 min",
    nextAvailable: "Monday",
     highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },

   // --- Brazil ---
   {
    id: "br-1",
    name: "Dr. Ana Silva",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 160,
    location: "São Paulo, Brazil",
    priceRange: "R$ 300 - 500",
    languages: ["Portuguese", "English", "Spanish"],
    conditions: ["Anxiety", "Body Image"],
    about: "Helping individuals build self-esteem and overcome body image issues.",
    experience: 11,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
   {
    id: "br-2",
    name: "Dr. Carlos Santos",
    title: "Psychoanalyst",
    image: "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 100,
    location: "Rio de Janeiro, Brazil",
    priceRange: "R$ 400 - 600",
    languages: ["Portuguese", "French"],
    conditions: ["Depression", "Existential Crisis"],
    about: "Specializing in Lacanian psychoanalysis for deep personal exploration.",
    experience: 20,
    sessionDuration: "50 min",
    nextAvailable: "Today"
  },
  {
    id: "br-3",
    name: "Ms. Julia Costa",
    title: "Family Therapist",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 55,
    location: "Brasília, Brazil",
    priceRange: "R$ 250 - 400",
    languages: ["Portuguese", "English"],
    conditions: ["Family Conflict", "Divorce"],
    about: "Supporting families through divorce and restructuring.",
    experience: 8,
    sessionDuration: "60 min",
    nextAvailable: "Thursday",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },

  // --- Germany ---
  {
    id: "de-1",
    name: "Dr. Hans Müller",
    title: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 85,
    location: "Berlin, Germany",
    priceRange: "€100 - €160",
    languages: ["German", "English"],
    conditions: ["Anxiety", "Depression", "OCD"],
    about: "Dr. Müller specializes in the treatment of anxiety and obsessive-compulsive disorders.",
    experience: 16,
    sessionDuration: "50 min",
    nextAvailable: "Tuesday",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "de-2",
    name: "Ms. Lena Weber",
    title: "Psychotherapist",
    image: "https://images.unsplash.com/photo-1554151228-14d9def656ec?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 60,
    location: "Munich, Germany",
    priceRange: "€90 - €140",
    languages: ["German", "English", "French"],
    conditions: ["Stress", "Life Transitions"],
    about: "Helping individuals navigate life transitions with clarity and resilience.",
    experience: 8,
    sessionDuration: "50 min",
    nextAvailable: "Today"
  },
   {
    id: "de-3",
    name: "Dr. Klaus Fischer",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 45,
    location: "Hamburg, Germany",
    priceRange: "€110 - €150",
    languages: ["German", "English"],
    conditions: ["Trauma", "PTSD"],
    about: "Expert in trauma therapy and EMDR.",
    experience: 12,
    sessionDuration: "60 min",
    nextAvailable: "Thursday"
  },

  // --- France ---
  {
    id: "fr-1",
    name: "Dr. Camille Laurent",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 95,
    location: "Paris, France",
    priceRange: "€90 - €150",
    languages: ["French", "English"],
    conditions: ["Relationship Issues", "Anxiety"],
    about: "Dr. Laurent offers a safe space for exploring relationship dynamics and personal growth.",
    experience: 14,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "fr-2",
    name: "Mr. Thomas Dubois",
    title: "Psychoanalyst",
    image: "https://images.unsplash.com/photo-1542596594-649edbc13630?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 50,
    location: "Lyon, France",
    priceRange: "€80 - €120",
    languages: ["French"],
    conditions: ["Depression", "Self-Esteem"],
    about: "Providing psychoanalytic therapy for self-discovery and healing.",
    experience: 10,
    sessionDuration: "50 min",
    nextAvailable: "Today"
  },
  {
    id: "fr-3",
    name: "Ms. Sophie Moreau",
    title: "Child Psychologist",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 70,
    location: "Marseille, France",
    priceRange: "€70 - €110",
    languages: ["French", "Arabic"],
    conditions: ["Child Development", "School Issues"],
    about: "Supporting children and adolescents with behavioral and school-related challenges.",
    experience: 7,
    sessionDuration: "45 min",
    nextAvailable: "Wednesday",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },

  // --- Japan ---
  {
    id: "jp-1",
    name: "Dr. Kenji Tanaka",
    title: "Psychiatrist",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.9,
    reviewCount: 110,
    location: "Tokyo, Japan",
    priceRange: "¥10,000 - ¥15,000",
    languages: ["Japanese", "English"],
    conditions: ["Work Stress", "Depression"],
    about: "Specializing in workplace mental health and treating burnout in professionals.",
    experience: 20,
    sessionDuration: "50 min",
    nextAvailable: "Tomorrow",
    highlights: [{ icon: "Video", label: "Available Online", color: "bg-green-100 text-green-800" }]
  },
  {
    id: "jp-2",
    name: "Ms. Yumi Yamamoto",
    title: "Counselor",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.8,
    reviewCount: 80,
    location: "Osaka, Japan",
    priceRange: "¥8,000 - ¥12,000",
    languages: ["Japanese", "English"],
    conditions: ["Anxiety", "Social Phobia"],
    about: "Helping individuals overcome social anxiety and build confidence.",
    experience: 10,
    sessionDuration: "50 min",
    nextAvailable: "Today"
  },
    {
    id: "jp-3",
    name: "Dr. Hiroshi Sato",
    title: "Clinical Psychologist",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300&h=300",
    verified: true,
    rating: 4.7,
    reviewCount: 50,
    location: "Kyoto, Japan",
    priceRange: "¥9,000 - ¥13,000",
    languages: ["Japanese"],
    conditions: ["Family Conflict", "Elderly Care"],
    about: "Supporting families dealing with aging and intergenerational conflict.",
    experience: 15,
    sessionDuration: "60 min",
    nextAvailable: "Friday"
  }

];

export const conditionsList = [
  "Anxiety", "Depression", "Trauma", "Bipolar Disorder", "ADHD",
  "Sleep Disorders", "Relationship Issues", "Family Conflict",
  "Parenting", "Cognitive Disorders", "Brain Injury", "Dementia",
  "Child Development", "School Issues", "Behavioral Problems",
  "Stress", "Life Transitions", "Grief", "Addiction", "OCD",
  "Body Image", "Men's Health", "Women's Issues", "Self-Esteem", "Work Stress", "Social Phobia", "Elderly Care"
];

export const languagesList = [
  "English", "Spanish", "Mandarin", "Hindi", "Gujarati", "Korean", "French", "German",
  "Arabic", "Somali", "Swahili", "Turkish", "Portuguese", "Japanese", "Russian", "Italian",
  "Cantonese", "Marathi", "Kannada", "Luo"
];
